
<!DOCTYPE html>
<html>
<head>
	<title>CODIGO</title>


	  <meta charset="utf-8">

<style type="text/css">
body {
	background-image: url(trafico.jpg);
	background-color: #FFF;
}
body,td,th {
	color: #FFF;
}
</style>

<body text="#FFFFFF"><nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                       <a class="navbar-brand" href="index.html">INFRACCIONAPP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling --><ul class="nav navbar-nav">
</head>
<body>
<iframe src="https://docs.google.com/viewer?url=http://www.uelbosque.edu.co/sites/default/files/bienestar/mobiendonos/codigo_nacional_transito.pdf&embedded=true" width="600" height="780" style="border: none;"></iframe>
</body>
</html>





